version: '3.3'

services:
  postgres:
    restart: unless-stopped
    image: postgres
    container_name: keycloak_postgres
    volumes:
      - ../keycloak_postgres_data:/var/lib/postgresql/data
    env_file:
      - keycloak.env
    environment:
      POSTGRES_DB: bdd_keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
    container_name: keycloak
    restart: unless-stopped
    image: jboss/keycloak:latest
    env_file:
      - keycloak.env
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: bdd_keycloak
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
